name: oasdiff
on: [ pull_request,workflow_dispatch ]
jobs:
  oasdiff-diff:
    runs-on: ubuntu-latest
    container:
      image: tufin/oasdiff:stable
    steps:
      - uses: actions/checkout@v3
      - run: |
          oasdiff \
            -base https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore.yaml \
            -revision https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore-expanded.yaml \
            -format text
  oasdiff-check-breaking:
    runs-on: ubuntu-latest
    container:
      image: tufin/oasdiff:stable
    steps:
      - uses: actions/checkout@v3
      - run: |
          oasdiff \
            -base https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore.yaml \
            -revision https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore-expanded.yaml \
            -check-breaking \
            -format text
