name: oasdiff
on: [ pull_request,workflow_dispatch ]
jobs:
  oasdiff-diff:
    runs-on: ubuntu-latest
    container:
      image: tufin/oasdiff:stable
    steps:
      - uses: actions/checkout@v3
      - run: |
          oasdiff \
            -base https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore.yaml \
            -revision https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore-expanded.yaml \
            -format text >result.txt

          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat result.txt)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        id: oasdiff-diff
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = ${{ steps.oasdiff-diff.outputs.result }};
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const bodyPrefix = `<!-- oasdiff-diff-result -->`;
            const body = `${bodyPrefix}
            ## Changes
            ${result}`;

            const { data: comments } = await github.rest.issues.listComments({ issue_number, owner, repo });
            const comment_id = comments.find((c) => c.body.startsWith(bodyPrefix))?.id;
            if (comment_id) {
              await github.rest.issues.updateComment({ comment_id, issue_number, owner, repo, body });
            } else {
              await github.rest.issues.createComment({ issue_number, owner, repo, body });
            }
  oasdiff-check-breaking:
    runs-on: ubuntu-latest
    container:
      image: tufin/oasdiff:stable
    steps:
      - uses: actions/checkout@v3
      - run: |
          oasdiff \
            -base https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore.yaml \
            -revision https://github.com/OAI/OpenAPI-Specification/raw/main/examples/v3.0/petstore-expanded.yaml \
            -check-breaking \
            -format text >result.txt

          echo "result<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat result.txt)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        id: oasdiff-check-breaking
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const result = ${{ steps.oasdiff-check-breaking.outputs.result }};
            const issue_number = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const bodyPrefix = `<!-- oasdiff-check-breaking-result -->`;
            const body = `${bodyPrefix}
            ## Breaking Changes
            ${result}`;

            const { data: comments } = await github.rest.issues.listComments({ issue_number, owner, repo });
            const comment_id = comments.find((c) => c.body.startsWith(bodyPrefix))?.id;
            if (comment_id) {
              await github.rest.issues.updateComment({ comment_id, issue_number, owner, repo, body });
            } else {
              await github.rest.issues.createComment({ issue_number, owner, repo, body });
            }
